# Generated by Django 6.0.5 on 2026-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("fan", "Fan"), ("athlete", "Athlete"), ("coach", "Coach")],
                default="fan",
                max_length=20,
            ),
        ),
    ]
